name: Roundhouse Development
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3216468975879252
title: 'Roundhouse Development - Natalie Kueneman, Web Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3e1ed'
    - '#85b7d0'
    - '#72a0b5'
    - '#007aa2'
    - '#148eaf'
  brandStrength: 0.1875
  lightness: 0.6350437682121992
  saturation: 0.22368607460521162
  rhythmicContrast: 0.4559261747635901
purpose: []
