name: Roundhouse Development
favicon: null
layout_spectrum: 0.5292060791980475
typography_spectrum: 0.3216468975879252
title: 'Roundhouse Development - Natalie Kueneman, Web Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.47554041165858507
  lightness: 0.6350437682121992
  saturation: 0.22368607460521162
  rhythmicContrast: 0.4559261747635901
purpose: []
