typography_spectrum: 0.36423807271359726
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.6440629911674464
  lightness: 0.8789948995080361
  saturation: 0.08838459255219908
  rhythmicContrast: 0.4045994412900862
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3393554243777353
analytics:
  google: null
  facebook: null
  twitter: null
name: Roundhouse Development
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Roundhouse Development
content: []
description: Natalie Kueneman - Web Development
purpose:
  - type: contact
    url: 'tel:4154253244'
    label: Call
  - type: contact
    url: 'mailto:info@roundhousedevelopment.com'
    label: Email
github: true
author:
  name: Natalie Kueneman
  email: info@roundhousedevelopment.com
  url: 'https://thegrid.ai/roundhouse-development/'
