name: Roundhouse Development
favicon: null
layout_spectrum: 0.23739
typography_spectrum: 0.50603
title: 'Roundhouse Development - Natalie Kueneman, Web Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bebebe'
    - '#cb89a5'
    - '#dc568b'
    - '#f1156f'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.4559261747635901
purpose: []
