layout_spectrum: 0.2852747163313008
typography_spectrum: 0.48616394239938865
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5756312946731796
  lightness: 0.8314676595092889
  saturation: 0.6947714658321278
  rhythmicContrast: 0.8907281989749005
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Natalie Kueneman
  email: info@roundhousedevelopment.com
  url: 'https://thegrid.ai/roundhouse-development/'
name: Roundhouse Development
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Services
    id: b5fc9ecc-a04d-4501-81fe-d938569ef34c
    type: content
  - name: Portfolio
    id: a3aaaea4-16fd-4643-924d-bd4c3a19b53d
    type: content
favicon: null
title: Roundhouse Development
content: []
description: Natalie Kueneman - Web Development
purpose:
  - type: contact
    url: 'tel:4154253244'
    label: Call
  - type: contact
    url: 'mailto:info@roundhousedevelopment.com'
    label: Email
