name: Roundhouse Development
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39388
title: 'Roundhouse Development - Natalie Kueneman, Web Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d5d5'
    - '#00999e'
    - '#f5907c'
    - '#022648'
    - '#91a0ae'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
