name: Roundhouse Development
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47388
title: 'Roundhouse Development - Natalie Kueneman, Web Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#808080'
    - '#04586c'
    - '#6c0478'
    - '#f4f4f4'
  brandStrength: 0.1875
  lightness: 0.6350437682121992
  saturation: 0.6875
  rhythmicContrast: 0.4559261747635901
purpose: []
