name: Roundhouse Development
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50603
title: 'Roundhouse Development - Natalie Kueneman, Web Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b80000'
    - '#007800'
    - '#c6ff1a'
    - '#f600e3'
  brandStrength: 0.25
  lightness: 0.6350437682121992
  saturation: 0.6875
  rhythmicContrast: 0.4559261747635901
purpose: []
